### PR TITLE
update base

### PR DESCRIPTION
**Pull request by bend-n**

### CODE REVIEW

**Comment by nilederg** [comment]
why

**Comment by bend-n** [comment]
> why

https://github.com/Apricot-Conservation-Project/base/commit/f7534f1e6de375ebfde893a51e0502ffe3dc09ae

but ill wait till next base update to merge

**Comment by nilederg** [comment]
huh. i don't know too much about github, so i'm going to trust you on this one

**Review by nilederg — APPROVED** [review]
approved only because nobody better could review this

**Comment by bend-n** [comment]
its jitpack

**Pull request merged**
